name: asset

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: ls
    - name: Build
      run: |
        echo "build"
        echo ${{ github.ref }}
        echo $(echo ${GITHUB_REF:10})
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: a.tar.gz
        asset_name: a.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        
  test:
      name: test windows docker
      runs-on: ubuntu-latest
      steps:
      - name: test
        run: docker version
      
