name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: repo
        run: |
          sudo apt update
          sudo apt-get install -y lsb-release dpkg gnupg gnupg2 aptly ca-certificates createrepo
          echo "${{ secrets.KEY_PRIVATE }}" >private.key
          sed -i "s/@version@/4.0.0/g; s/@revision@/1/g; s/@passphrase@/${{ secrets.PASSPHRASE }}/g;" repo.sh
          chmod +x repo.sh
          sudo ./repo.sh
          ls ~/.aptly/public
      - id: path
        run: echo ::set-output name=path::$(ls ~)/.aptly/public
      - uses: actions/upload-artifact@v1
        with:
          name: baetyl-i386
          path: ${{ steps.path.outputs.path }}
