name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: repo
        run: |
          echo "jekk"
      - uses: actions/upload-artifact@v1
        with:
          name: baetyl-repo
          path: $(pwd)/main.go
