name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: repo
        run: |
          sudo apt update
          sudo apt-get install -y lsb-release dpkg gnupg gnupg2 aptly ca-certificates createrepo
          echo "${{ secrets.KEY_PRIVATE }}" >private.key
          sed -i "s/@version@/$(git tag --contains HEAD)/g; s/@revision@/1/g; s/@passphrase@/${{ secrets.PASSPHRASE }}/g;" scripts/repo.sh
          ./repo.sh
